//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concurenta
    {
        public int ID { get; set; }
        public string Nume { get; set; }
        public string Descriere { get; set; }
        public System.DateTime DataAdaugarii { get; set; }
    }
}
